### PR TITLE
fix: show avatar in post and ratings

### LINKED ISSUE #195: Bug: Display correct avatar for ratings and posts

### PR DESCRIPTION
**Pull request by Mariinja**
closes #195

### CODE REVIEW

File: src/components/course/post/PostComment.tsx [hunk 1]
```diff
@@ -1,40 +1,38 @@
...
-          <Avatar alt="Remy Sharp" src={user.avatar} />
-        </Grid>
-        <Grid justifyContent="left" item xs zeroMinWidth>
-        <Box sx={{ ...commonStyles, borderRadius: '16px' }}>
-          <Typography sx={{ marginLeft: "10px" }}>{text}
-          </Typography>
+    <Grid container wrap="nowrap" spacing={2} style={{ padding: "5px" }}>
+      <Grid item>
+        <Tooltip title={user.username}>
+          <Avatar alt="Remy Sharp" src={getAvatar(user.avatar)} />
```
Comment (StefanieKrohmann) [inline src/components/course/post/PostComment.tsx:28]: if we have the alt attribute maybe change it to "user avatar" instead of "Remy Sharp", which does not add any additonal value

**Review by StefanieKrohmann — APPROVED** [review]

**Review by StefanieKrohmann — APPROVED** [review]
